# Generated by Django 6.0.5 on 2026-05-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='payment_method',
            field=models.CharField(choices=[('qr', 'Предоплата по QR-коду'), ('mir', 'Оплата картой МИР'), ('office', 'Постоплата в офисе организации')], max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
